# Generated by Django 4.1.3 on 2023-03-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcart',
            name='discount_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalcart',
            name='total_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
